site_name: Drupal 8
nav:
  - Einführung:
    - Versionen: introduction/index.md
    - Benutzeroberfläche: introduction/ui.md
    - Technische Aspekte: introduction/technical.md
  - Site Building:
    - Entities: site-building/entities.md
    - Views: site-building/views.md

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
