site_name: Drupal 8
nav:
  - Einführung:
    - Versionen: introduction/index.md
    - Drupal-Benutzeroberfläche: introduction/ui.md
    - Unterschiede Drupal 7/8:
      - Benutzeroberfläche: introduction/d7-d8-diff/ui.md
      - Technische Aspekte: introduction/d7-d8-diff/technical.md
  - Website-Aufbau (Site Building):
    - Konfiguration: site-building/configuration.md
    - Benutzer (Users): site-building/users.md
    - Entitäten (Entities): site-building/entities.md
    - Blöcke (Blocks): site-building/blocks.md
    - Ansichten (Views): site-building/views.md
    - Menüs (Menus): site-building/menus.md
    - Themes: site-building/themes.md

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
