site_name: Drupal 8
nav:
  - Home: index.md
  - Einführung:
    - Versionen: introduction/versions.md
    - Drupal-Benutzeroberfläche: introduction/ui.md
  - Website-Aufbau (Site Building):
    - Module: site-building/modules.md
    - Konfiguration: site-building/configuration.md
    - Entitäten und Felder (Entities, Fields): site-building/entities-fields.md
    - Benutzer (Users): site-building/users.md
    - Blöcke (Blocks): site-building/blocks.md
    - Ansichten (Views): site-building/views.md
    - Menüs (Menus): site-building/menus.md
    - Themes: site-building/themes.md
    - Sonstiges: site-building/misc.md
  - Unterschiede Drupal 7/8:
    - Benutzeroberfläche: d7-d8-diff/ui.md
    - Technische Aspekte: d7-d8-diff/technical.md

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
